display:
  model: 2in13_V3
  full_clear_after: 30
  rotate_deg: 180

modules:
  - clock
  - home_assistant
  - flightradar24

clock: 
  date_format: "%d/%m/%y"
  time_format: "%H:%M"
  time_pos: [60, 25]
  date_pos: [75, 65]

home_assistant:
  ip: "http://ip:8123"
  token: "token"
  entity: "sensor.outdoor_sensors_ds18b20_temperature"
  pos: [15, 80]

flightradar24:
  lat: 47.69356464899508
  lon: 99.688212871551517
  radius: 10000
  pos: [30, 3]