date: 
  format: "%d/%m/%y"

time: 
  format: "%H:%M"

display:
  full_clear_after: 30
  rotate_deg: 180

home_assistant:
  ip: "HA IP here"
  token: "HA token here"
  entities:
    - "sensor.ds18b20_examplee_temperature"